### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#23]
https://ucsdlib.github.io/git-novice/09-conflict/

I've rarely had enough time to cover this section, fwiw. Open to what you all think about the value of this vs the other sections.

**Comment by dunn** [comment]
I forgot I assigned this to myself.

Do we have time for it?  If so, should we use a GUI editor to do conflict resolution?  Which one?

**Comment by dunn** [comment]
@chrissyrissmeyer do you want to do this in GitKraken?  Would you rather incorporate it into the merging section, or just have it be a non-interactive demo?

**Comment by chrissyrissmeyer** [comment]
I think that conflicts are one of the scariest parts of working in Git, in my opinion, so I'd like to see us include it. Not sure if I am the right person to update though since I don't have much experience with them (and they freak me out...). Open to do a GUI demo, but I worry about introducing this prior to the GUI section. Either way, I think we need to move this after remotes and collaborating, especially because of this sentence: "As soon as people can work in parallel, it’s likely someone’s going to step on someone else’s toes. "

**Comment by dunn** [comment]
> Not sure if I am the right person to update though since I don't have much experience with them (and they freak me out...). 

All the more reason :smile_cat:

> I think we need to move this after remotes and collaborating

Makes sense.  Maybe we could frame it as 'one area command-line git is _not_ good is resolving merge conflicts, so here's this GUI tool (more are listed in the resources section)'.

**Comment by chrissyrissmeyer** [comment]
>All the more reason :smile_cat:

fine fine fine

**Comment by dunn** [comment]
<3

**Comment by chrissyrissmeyer** [comment]
https://github.com/ucsdlib/git-novice/pull/94
